### ISSUE TITLE
ElvUI Dev officially support boss6+ (in development)

### ISSUE THREAD

**Issue by kodewdle** [GabeStah/kExtraBossFrames#1]
[Compare](https://github.com/tukui-org/ElvUI/compare/9f091dd462d01cfc4c5a6e7b6fa3415151712d7e...3e04c1e30414d68e475450d7de780e8d420c9bf7)

- We just officially added support for `boss6`+ which doesn't require `OnUpdate` `UpdateAll`; this patch will let the `boss6`+ frames handle like `*target` units (which get updated at a set interval)
- To prevent incompatibly we've [blacklisted](https://github.com/tukui-org/ElvUI/compare/3e04c1e30414d68e475450d7de780e8d420c9bf7...7f3311c5c9366f0ea9150df2360a49d7a55f9f3f) this when they are not using SUF in order to prevent FPS loss of firing `UpdateAll` at a specific rate (hitting every element).

**Comment by kodewdle** [comment]
an update, we released [12.72](https://github.com/tukui-org/ElvUI/releases/tag/v12.72) which means, this change was put in place and this addon will automatically be disabled when the user is not using SUF as stated above.

**Comment by GabeStah** [comment]
That's great to hear that ElvUI has built-in support!  I'll remove ElvUI from the addon in the future, but for now I've updated the README.
